config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :goals

  resources :tags

  resources :sessions, only: [:new, :create]

  delete 'logout' => 'sessions#destroy'

  get 'featured' => 'stories#featured'

  scope defaults: {format: :json} do
    resources :stories
  end

  root 'home#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :desc, :user_id, presence: true
  belongs_to :users
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :story_tags, class_name: "StoryTag"
  has_many :tags, :through => :story_tags
  validates :title, :text, :user_id, presence: true
  belongs_to :users
  scope :featured, -> { where(featured: true) }
  scope :active, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }
  scope :published, -> { where(published: true) }
  accepts_nested_attributes_for :tags
end

app/models/story_tag.rb
class StoryTag < ActiveRecord::Base
  belongs_to :story
  belongs_to :tag
end

app/models/story_with_hashtag.rb
class StoryWithHashtag < ActiveRecord::Base
  belongs_to :stories
  belongs_to :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :story_tags
  has_many :stories, :through => :story_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, :password_digest, presence: true
  validates_uniqueness_of :email
  has_secure_password
  has_many :goals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  def index
    @goals = Goal.where(user_id: current_user.id)
    render json: @goals, except: [:created_at, :updated_at]
  end

  def show
    @goal = Goal.find_by_id(params[:id])
    render json: @goal, except: [:created_at, :updated_at]
  end

  def create
      @goal = Goal.new(goal_params)
      @goal.user_id = current_user.id
      @goal.save
      render json: @goal, except: [:created_at, :updated_at]
  end

  def save
  end

  def destroy
      Goal.find_by_id(params[:id]).destroy
      render json: @goal, except: [:created_at, :updated_at]
  end

  private
    def goal_params
      params.require(:goal).permit(:title, :desc)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
    else
      flash[:notice] = "Cannot login"
    end
    redirect_to root_path
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  respond_to :json

  def index
    if (current_user)
      @stories = Story.active.where(user_id: current_user.id)
    else
      @stories = Story.active.published
    end
  end

  def featured
    @stories = Story.published.featured.active
    render :index
  end

  def destroy
    @story = Story.find_by_id(params[:id])
    @story.archived = true
    @story.save
    render json: @story, except: [:created_at, :updated_at]
  end

  def show
    @story = Story.find_by_id(params[:id])
  end

  def create
      @story = Story.new(story_params)
      @story.user_id = current_user.id
      @story.archived = false
      @story.featured = false
      @story.published = false
      @story.save
      render json: @story, except: [:created_at, :updated_at]
  end

  def update
    @story = Story.find_by_id(params[:$story][:id])
    @story.title = params[:$story][:title]
    @story.text = params[:$story][:text]
    @story.featured = params[:$story][:featured]
    @story.published = params[:$story][:published]
    @hashtags = []
    params[:hashtags].each do |t|
      tag = Tag.find_by(hashtags: t)
      if tag == nil
        tag = Tag.create(hashtags: t)
      end
      @hashtags << tag.id
    end
    @story.tag_ids = @hashtags
    @story.save
    render :show
  end

  private
    def story_params
      params.require(:story).permit(:title, :text)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    render json: @tags, except: [:created_at, :updated_at]
  end

  def show
    @matches = Tag.where(id: params[:id])
    render json: @matches, except: [:created_at, :updated_at]
  end

  def create
      @tag = Tag.new(hashtags: params[:hashtag])
      @tag.save
      render json: @tag, except: [:created_at, :updated_at]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users, except: [:created_at, :updated_at]
  end
  
  def new
  end

  def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome #{@user.username}!"
        redirect_to root_path
      else
        flash[:notice] = "Error #{@user.errors.full_messages}"
        redirect_to new_user_path
      end
  end
  
  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="">
  <% flash.each do |name, msg| %>
  <% content_tag :div, msg, class: "alert #{name == 'error' ? 'alert-danger' : 'alert-info'}" %>
  <% end %>
</div>

<% if !current_user %>
  <div class="app">
      <%= form_for :user, url: sessions_path do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <br>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <br>
        <%= f.submit "Login" %>
      <% end %>
  </div>
<% end %>
<div class="app">
<ui-view></ui-view>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- Angular -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>
<!-- UI-Router -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.18/angular-ui-router.min.js"></script>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- bootstrap css -->
  <link type="text/css"
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/ratchet/2.0.2/css/ratchet.min.css">
  <link type="text/css"
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/ratchet/2.0.2/css/ratchet-theme-ios.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<html lang="en" ng-app="growth_tracker">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <header class="bar bar-nav">
    <% if current_user.present? %>
      <h1 class="title">
      <% if content_for? :title %>
        <%=yield :title %>
      <% else %>
        Hello <%= current_user.username %>!
      <% end %>
      </h1>
      <% if content_for :back %>
        <button class="btn" style="float: left">
          <%=yield :back%>
        </button>
      <% end %>
      <button class="btn" style="float: right">
        <%= link_to "Logout", logout_path, method: :delete %>
      </button>
    <% else %>
      <h1>Hello!
      <button class="btn" style="float: right">
        <%= link_to "Sign up", new_user_path, method: :get %>
      </button>
      </h1>
    <% end %>
  </header>
  <%= stylesheet_link_tag    'app', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'app', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body ng-controller="MainCtrl">
     <%= yield %>
</body>

<% if current_user %>
<nav class="bar bar-tab">
  <a class="tab-item" ui-sref="main">
    <span class="icon icon-home"></span>
    <span class="tab-label">Home</span>
  </a>
  <a class="tab-item" ui-sref="goals">
    <span class="icon icon-share"></span>
    <span class="tab-label">Goals</span>
  </a>
  <a class="tab-item" ui-sref="stories">
    <span class="icon icon-list"></span>
    <span class="tab-label">Stories</span>
  </a>
</nav>
<% end %>

</html>

app/views/users/create.html.erb
<%= @user.email %>

app/views/users/new.html.erb
<div class="app">
  <%= form_for :user, url: users_path do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit "Sign Up" %>
  <% end %>
</div>
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
<%= link_to "Home", root_path %>

app/views/users/show.html.erb
<%= @user.email %>